### ISSUE TITLE
[DEPLOYMENT] Starting workers via ssh or php hangs shell

### ISSUE THREAD

**Issue by mfn** [wa0x6e/Cake-Resque#75]
Trying to start workers from other processes hangs the shell:

```
$ php -r 'passthru("Console/cake CakeResque.CakeResque start --queue test; echo foo");'
Creating workers
Starting worker ... Done

foo
^C
```

What's happening here is that the shell is never returned to the user, although executing `Console/cake CakeResque.CakeResque start --queue test` does.

Another observation is that there is actually another command in my test which gets executed (`echo foo`) -> but the whole command, executed in a subshell through php, never returns.

This is the most simplified case I came up with; the higher goal is automating of deployment via e.g. ssh and phing. I have both setups already running, but all hang when starting workers.

I looked at CakeResque and saw quite some sophisticated usage of subshells, nohup, pcntl; but it doesn't dawn me what could lead to the hang.

I tried `strace` but it floods my screen and I'm unable to pinpoint anything obvious:

```
$ strace -f php -r 'passthru("Console/cake CakeResque.CakeResque start --queue test");'
... snipped thousands of lines
[pid 28293] rt_sigprocmask(SIG_SETMASK, 0x7fffed271030, NULL, 8) = 0
[pid 28293] nanosleep({...}, ^CProcess 28276 detached
```

I was able to reproduce this behaviour in three environments: one VM, two physical machines (two Ubuntu (precise and trusty) and Debian (squeeze). I tested this with cake-resque 4.1.0 in environments with php 5.4 and 5.5 .

I tested using other means of starting them, e.g. via ruby: this works locally but also hangs when executed via ssh: `ruby -e 'system("Console/cake CakeResque.CakeResque start --queue test")'`.

I could work around this by starting them in the background, but I need to see the output and verify they properly started.

I've never seen such a behaviour before, any pointers/hints much appreciated.

**Comment by dilab** [comment]
Facing the same issue when trying to start a worker using Phing.

**Comment by mfn** [comment]
@dilab See https://github.com/wa0x6e/Cake-Resque/pull/76 and try if it works for you

**Comment by jbourassa** [comment]
I've had the same issue, my workaround has been to redirect all output to /dev/null. That's obviously not a good solution since errors are no longer reported, but meh, at least I can deploy.

**Comment by wa0x6e** [comment]
Does your system support `nohup` ?

Seems like the shell is hanging because it's waiting for a response from resque, but resque goes in an infinite loop internally, and does not return anything.

There's 2 thing in place to prevent: `nohup` and the output redirect to null.

**Comment by jbourassa** [comment]
@wa0x6e I would assume so, I'm deploying to Ubuntu 14.04 (from OSX, but I don't think that matters).

**Comment by wa0x6e** [comment]
Does the command works hang only when run via a php ?

If yes, I do recommend a deployment tool such as Capistrano, that does not use php to execute system command. There's already a `passthru` inside CakeResque, and calling it on top of another `passthru` seems weird, and hard to debug.

**Comment by jbourassa** [comment]
No, this also hangs:

```
$ ssh user@server 'cd /path/to/cake; bin/cake CakeResque.CakeResque start'

Creating workers
Starting worker ..
.
 Done
[hanging forever]
```

PS: Thanks for your help, I appreciate.

**Comment by wa0x6e** [comment]
Can you try again by loging to ssh first, _then_ calling the rest of the command ?

It's sadly not the same environment.

**Comment by jbourassa** [comment]
Oh, that works. It only _breaks_ when calling it from ssh as a command, not in an interactive shell.

**Comment by wa0x6e** [comment]
Interactive shell has been causing issue for a long time.

http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/#

**Comment by mfn** [comment]
Closing, no longer using CakeResque
